services:
  init:
    image: &tempoImage grafana/tempo:2.6.0
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - tempo-data:/var/tempo

  backend:
    image: djajcevic/cool-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:myh2db
      OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:9317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_SERVICE_NAME: backend
      OTEL_JAVAAGENT_DEBUG: false
      OTEL_TRACES_EXPORTER: otlp
      OTEL_SPAN_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./otel/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    volumes:
      - grafana-data:/var/lib/grafana
      - ./otel/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - tempo
    networks:
      - observability

  tempo:
    image: *tempoImage
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "4317"  # otlp grpc
      - "4318"  # otlp http
      - "9411"   # zipkin
    volumes:
      - tempo-data:/var/tempo
      - ./otel/grafana/tempo.yaml:/etc/tempo.yaml
    depends_on:
      - init
    networks:
      - observability

  alloy:
    image: grafana/alloy:latest
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:4317
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    volumes:
      - ./otel/grafana/config.alloy:/etc/alloy/config.alloy
    ports:
      - "12345:4317" # otlp
      - "9317:9317"
      - "12346:12346" # faro
    networks:
      - observability
      - app

volumes:
  grafana-data:
  tempo-data:

networks:
  observability:
  app: