#$schema: https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: %{{cookiecutter.project_slug}}%
  annotations:
    github.com/project-slug: djajcevic/%{{cookiecutter.project_slug}}%-acs
    backstage.io/environment: dev
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=%{{cookiecutter.project_slug}}%'
  tags:
    - java
spec:
  type: service
  lifecycle: development
  owner: demo-team
  system: demo
  dependsOn:
    - component:default/%{{cookiecutter.project_slug}}%-acr