#$schema: https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: %{{cookiecutter.project_slug}}%
  annotations:
    github.com/project-slug: djajcevic-idp/%{{cookiecutter.project_slug}}%-acs
    backstage.io/environment: dev
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=%{{cookiecutter.project_slug}}%-bff'
    argocd/app-name: %{{cookiecutter.project_slug}}%
    sonarqube.org/project-key: default/%{{cookiecutter.package}}%:%{{cookiecutter.project_slug}}%
  tags:
    - java
  links:
    - url: https://%{{cookiecutter.project_slug}}%.apps.idp.dhl.com/api
      title: API
      icon: star
spec:
  type: service
  lifecycle: development
  owner: demo-team
  system: demo
  dependsOn:
    - component:default/%{{cookiecutter.project_slug}}%-acr
  providesApis:
    - %{{cookiecutter.project_slug}}%
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: %{{cookiecutter.project_slug}}%
spec:
  type: rest
  lifecycle: deprecated
  owner: demo-team
  definition:
    $text: https://%{{cookiecutter.project_slug}}%.apps.idp.dhl.com/api/api-docs