#$schema: https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: %{{cookiecutter.project_slug}}%-acr
  annotations:
    argocd/app-name: %{{cookiecutter.project_slug}}%
  tags:
    - helm
spec:
  type: config-repo
  lifecycle: development
  owner: demo-team
  dependsOn:
    - component:default/%{{cookiecutter.project_slug}}%