#$schema: https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: %{{cookiecutter.project_slug}}%
  annotations:
    github.com/project-slug: djajcevic-idp/%{{cookiecutter.project_slug}}%-acs
    backstage.io/environment: dev
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=%{{cookiecutter.project_slug}}%'
    argocd/app-name: %{{cookiecutter.project_slug | replace("-frontend", "")}}%
    sonarqube.org/project-key: default/%{{cookiecutter.project_slug}}%
    backstage.io/techdocs-ref: 'dir:.'
    demo.backstage.io/techdocs-builder: 'local'
  tags:
    - react
    - js
  links:
    - url: https://%{{cookiecutter.project_slug | replace("-frontend", "")}}%.apps.idp.dhl.com
      title: Website
      icon: star
spec:
  type: website
  lifecycle: development
  owner: demo-team
  system: demo
  dependsOn:
    - component:default/%{{cookiecutter.project_slug | replace("-frontend", "")}}%